### ISSUE TITLE
Repeated use of await expression does not compile when rewriting `AwaitAsyncCall`

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#109]
---

Author Name: **Eduard Kamburjan** (Eduard Kamburjan)
Original Redmine Issue: 196, https://envisage.ifi.uio.no:8080/redmine/issues/196
Original Date: 2016-05-19

---

The attached file does not compile with the Erlang-backend:

```
./fut.abs:0:0:Expected a future type, but found type <UNKNOWN> instead.
./fut.abs:0:0:Name tmp755024773 cannot be resolved.

Compilation failed with syntax errors.

```

It does compile if any of the await obj!method() expressions is resolved by hand. Compiles with other backends.

**Comment by rudi** [comment]
Attached file:
```
module Test;

data AccelState = DUMMY;
data Information = DUMMYINFO;

interface Node {Information triggerFront(I t); }
interface Edge {Node getTo(Node n);}

interface I { Unit arriveFront(Rat delay, AccelState newState); }
class C implements I { 
	AccelState state = DUMMY;
	Edge edge = null;
	Node node = null;
 	Unit arriveFront(Rat delay,  AccelState newState){
		await duration(delay,delay);
		state = newState;
 		Node n = await edge!getTo(node);
		Information li = await n!triggerFront(this);
	} 
} 

{
	println("test");
}
```

**Comment by rudi** [comment]
This seems related to the `AwaitAsyncCall` rewriting done in `GenerateCoreAbs.jadd`; the `tmpxxxx` variables are generated there.

**Comment by VolkerStolz** [comment]
Add data point: the 'await duration' is not significant, a 'skip' instead will do just "fine".

**Comment by rudi** [comment]
I tentatively blame `frontend/src/abs/backend/coreabs/GenerateCoreABS.jadd` lines 125-144.  We modify the statement list of a block in-place (destructively) and `return this` after finishing the rewrite.  Should we create a new `Block` object and selectively copy over the untouched statements instead?  Creating a new object might break fewer JastAdd invariants.

**Comment by VolkerStolz** [comment]
The problem with any block-based solution is scoping: at least currently the necessary variable is used inside the (special type of) block, which is why the postprocessing is necessary to lift everything from inside the block back into the body. A "mixed" approach might work: I could try to create the variable declaration before the block, that might be reasonably safe...

**Comment by rudi** [comment]
I think that's not quite the point I was trying to make.  Specifically, I'm not talking about the `Stmt` => `RewriteBlock` rule, but about the `Block` => `Block` one (starting at Line 125).

Currently we destructively modify the block and return the same block; I propose testing if creating a fresh block and filling it with the desired statement list works.

On second thought, maybe we can skip the whole `Stmt` => `RewriteBlock` dance and simply do

    rewrite Block when (this.hasAsyncAwaitCall()) to Block { return new Block(makeDesiredStmtList(...)) }

?

**Comment by VolkerStolz** [comment]
Remind me, did I (or someone) add a unit-test for that?
