### ISSUE TITLE
Erlang backend tests taking too long

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#113]
---

Author Name: **Volker Stolz** (Volker Stolz)
Original Redmine Issue: 205, https://envisage.ifi.uio.no:8080/redmine/issues/205
Original Date: 2016-07-27

---

The Erlang unit tests take 1:10h on top of the 20 mins for the other tests. We clearly should split up the CI-tests.

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Volker Stolz** (Volker Stolz)
Original Date: 2016-07-28T08:58:59Z

---

I split off the tests in the CI.

It seems the unit-tests (and probably Eclipse-land in its entirety) don't see the precompiled Erlang-code, so there's some potential for optimization.

**Comment by rudi** [comment]
Running `rebar compile` in directory `frontend/src/abs/backend/erlang/runtime/absmodel` in the source tree (before compiling the frontend) might help.  Just verified that running the unit tests from within eclipse picks up the precompiled libraries that way.

**Comment by VolkerStolz** [comment]
rebar? Or rebar3?

$ ./rebar3 
Rebar3 is a tool for working with Erlang projects.

**Comment by VolkerStolz** [comment]
Add datapoint: just precompiling before launching Eclipse doesn't help for the unit test. We will survive.

**Comment by rudi** [comment]
`frontend/src/abs/backend/erlang/runtime/bin/rebar` :)
