### ISSUE TITLE
Inherited interface does not expose method to Model API

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#123]
Given an interface that exposes a method to http, this method will not be exposed via a subinterface.

Reported by @cdegouw

**Comment by rudi** [comment]
Do you have an example?  The following works:

```
module Test;

interface I {
    [HTTPCallable] String getInfo();
}

interface I2 extends I { }

class C implements I2 {
    String getInfo() { return "Hello!"; }
}

{
    [HTTPName: "foo"] new C();
}
```

**Comment by cdegouw** [comment]
Hi Rudi,

I think this was fixed a long time ago. I guess whoever fixed it forgot to
mark it as such

2017-06-14 14:45 GMT+02:00 Rudi Schlatte <notifications@github.com>:

**Comment by rudi** [comment]
Thanks for the feedback!  I'll go ahead and close the bug.
