### ISSUE TITLE
Type checker can't find method in async call if it was added by delta

### ISSUE THREAD

**Issue by rm2340** [abstools/abstools#134]
Under some circumstances the type checker can't find a method when it is called using the shortcut `await o!m()`.

Consider the following example (compile with `absc -v -product=P test.abs`)
```
module M;

interface X {}
class X implements X {}
class Y {
    Unit m(X x) {}
}
{}

delta D;
modifies interface M.X {
    adds Bool m();
}
modifies class M.X {
    adds Bool m() { return True; }
}
modifies class M.Y {
    modifies Unit m(X x) {
        Bool res = await x!m();
    }
}

productline PL;
features F;
delta D when F;
product P(F);
root FM {
    group allof { opt F }
}
```
However, it does seem to work when calling the method using 
`Fut<Bool> f = x!m(); await f?; Bool res = f.get;`

**Comment by VolkerStolz** [comment]
On 08/12/2016 18:42, Radu wrote:
> Under some circumstances the type checker can't find a method when it is
> called using the shortcut |await o!m()|.

Yeah, there's another bug already reported. My code in there either
needs another human sacrifice or we need to flip the global switch to
disable it :-/

  -Volker

**Comment by rm2340** [comment]
That sounds scary 8-)

**Comment by rudi** [comment]
> On 9 Dec 2016, at 14:19, Volker Stolz <notifications@github.com> wrote:
> 
> On 08/12/2016 18:42, Radu wrote:
> > Under some circumstances the type checker can't find a method when it is
> > called using the shortcut |await o!m()|.
> 
> Yeah, there's another bug already reported. My code in there either
> needs another human sacrifice or we need to flip the global switch to
> disable it :-/

I’ll have a poke next week; I have a vague idea on how to simplify it, and maybe some bugs fall out during that process.

Rudi
