### ISSUE TITLE
Task scheduling issue

### ISSUE THREAD

**Issue by rm2340** [abstools/abstools#135]
Consider the following code. I would expect this to run to completion no matter how the tasks are scheduled, which indeed happens using the Java backend. Using the Erlang backend the program seems to hang, probably because the task that runs `m()` in response to the call by `r2` is never scheduled. Btw, replacing `suspend` with `await duration(1,1);` gives the expected behaviour.

```
module Test;

interface Env { Unit m(Int x); }
class Env implements Env {
    Int flag = 0;
    Unit m(Int x) {
        flag = x;
        while(flag == 0) {
            suspend;
            //await duration(1,1);
        }
        println("done");
    }
}

interface R { Unit run(); }
class R(Env env, Int x) implements R {
    Unit run() {
       await env!m(x);
    }
}

{
    Env env = new local Env();
    R r1 = new R(env,0);
    R r2 = new R(env,1);
}
```

**Comment by rudi** [comment]
`m` is busy-looping, and assumes a fair scheduler.  `await duration` forces scheduling of the other task and is not semantically equivalent to `suspend`.  Consider using `await flag != 0` instead.

I will investigate the possibility of a round-robin scheduler which should be more fair, but this code relies on behavior of the cog that is not guaranteed by the language semantics.

**Comment by rudi** [comment]
Added a random scheduler instead since that lets us keep a set of runnable processes instead of a list.
