### ISSUE TITLE
Invalid Java code generated for synchronous calls without assignment

### ISSUE THREAD

**Issue by rm2340** [abstools/abstools#139]
Consider this example:
```module Test;
interface I { Int foo(); }
class C implements I { Int foo() { return 7; } }
{
    I o1 = new C();
    Int z = o1.foo();
    o1.foo();
}
```
The call to `foo()` without assignment on the last line leads to a compilation error when compiling to Java.

**Comment by rudi** [comment]
Should be fixed in ceabcf55dd6203cf9a75ed3e5bdcc4b7ffd6926f
