### ISSUE TITLE
In this certain case, await on condition doesn't wait

### ISSUE THREAD

**Issue by rm2340** [abstools/abstools#143]
Shouldn't this code wait forever? (It doesn't.)

```
module Test;
class C {
    Unit run() {
        await False;
        println("Condition is true");
    }

}
{ new C(); }
```

**Comment by rudi** [comment]
When no process is runnable or waiting for anything that can become true, the model terminates.  To keep a model running after coming to a quiescent state, start the model API (i.e., "gen/erl/run -p 8080" instead of "gen/erl/run").

**Comment by rm2340** [comment]
OK, thanks for the clarification.
