### ISSUE TITLE
Old models fail to compile with current version

### ISSUE THREAD

**Issue by Edkamb** [abstools/abstools#170]
The following program fails to compile with the error message "Compilation of generated erlang code failed with exit value 1" when using the newest version of the compiler, but works fine with an older .jar .

Same for some of our bigger models.
```
module Test;

class C {
    Int i = 0;
    Unit m(){
        await duration(5,5);
        await i>0;
    }
}

{
    new C(); 
}
```

**Comment by rudi** [comment]
"works on my machine", which doesn't help us very much :)
Could you attach the output when compiling with `-v -debug`?  Thanks!

**Comment by Edkamb** [comment]
```
Analyzing Model...
Typechecking Model...
Generating Erlang code in gen/erl
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
Compilation of generated erlang code failed with exit value 1
```

**Comment by rudi** [comment]
hmm, that doesn't tell us much either. :/ Can you zip up the `gen/` directory and send it to me via mail?
