### ISSUE TITLE
Continuous Integration not ready for Java 8

### ISSUE THREAD

**Issue by VolkerStolz** [abstools/abstools#188]
The Buckminster CI configuration in ```.releng``` does not deal with Java 8 in Eclipse land. I quickly looked into it, but failed to get a working Buckminster instance on my local machine for further testing of a solution:

`
Error: file /uio/kant/ifi-diverse-u00/envisage/srv/jenkins/jobs/ABS-All-Bucky/workspace/frontend/src/abs/common/TreeUtilsHelper.java, line 116: Type mismatch: cannot convert from Stream<Object> to Stream<N>
`

If someone wants to beat me to it, you're welcome -- I've switched the now continuously failing build to "manual" in Jenkins.

**Comment by rudi** [comment]
Somewhat fixed by using https://circleci.com/gh/abstools/abstools instead
