### ISSUE TITLE
Class parameters cannot be named "fun"

### ISSUE THREAD

**Issue by larstvei** [abstools/abstools#194]
The following ABS program does not compile with the Erlang backend:

```
module Fun;

class A(String fun) {

}

{
}
```

If we change the string parameter `"fun"` to e.g. `"fn"`, then it compiles just fine.

The generated `class_Fun_A.erl` contains the following:

```
'get_all_state'(S)->
    [
        { 'fun', S#state.fun }
    ].
```

`fun` is a keyword in Erlang, so using it in the name of a record causes problems.

Calling it a low priority issue, because few will run into this issue.

**Comment by rudi** [comment]
Also fails for normal fields named `fun`
