### ISSUE TITLE
Multi-line strings, string interpolation

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#205]
Probably best to use JavaScript notation

```
`ab${x}cd`
```
is equivalent to `"ab" + toString(x) + "cd"`

**Comment by rudi** [comment]
In my code there's almost always something like

    println("x: " + toString(x) + ", y + 1: " + toString(y + 1));

I'd like to have this instead:

    println(`x: ${x}, y + 1: ${y + 1}`);

This is Javascript notation; as far as I know, these strings can include newlines.  Python (and apparently Kotlin) use triple quotes for multiline strings but for me the main benefit is the expression interpolation.

**Comment by rudi** [comment]
These strings would, of course, be rewritten into the first form in the AST in the usual way.  :)

**Comment by BjoernPetersen** [comment]
So with that syntax, would
```
println(`foo
bar`)
```
be printed as
```
foo
bar
```
or `foobar`/`foo bar`?

**Comment by rudi** [comment]
The way I understand it, it would be
    foo
    bar

**Comment by BjoernPetersen** [comment]
That's great, I like that. I wish Java had something like that, it sure would make writing ABS code for tests more convenient.

**Comment by rudi** [comment]
FWIW, in JavaScript
```
process.stdout.write(`foo
bar`);
```
prints
```
foo
bar
```

I'm very open to syntax discussions though!  ``` vs `"""`, etc.  :)

**Comment by rudi** [comment]
Implementation note: a template string will be a sequence of (StringLiteral | PureExp); this can likely be produced by the parser already.

**Comment by rudi** [comment]
Implemented in 41544c2ee50add6b94a5c1e0af8c6d857366b659

**Comment by rudi** [comment]
I chose a syntax
   `abc«expression»def`
-- inspired by xtext and leaves the lexer / parser stateless but not the easiest to type.  I'll solicit alternative notations on the mailing list.

**Comment by rudi** [comment]
While writing a question to the list, I decided that `$...$` is strictly better than the guillemets -- changed the implementation in 59ed228ac843e9c73fcb96a5459d0130b61d917d.
