### ISSUE TITLE
Misplacement of import/export clauses causes no error in the frontend

### ISSUE THREAD

**Issue by Edkamb** [abstools/abstools#267]
The following code should throw a type or parser error because a type declaration is before the import/export clauses, but only generates a warning `1:0:Warning: no main block found.` and compiles, but fails to generate executable code. `--prettyprint` shows that the after the type declaration, no further code is handled.

```
module Test;

data Spec = A | B;

import * from Test2;
export *;

{   println("done"); }

module Test2;
```

**Comment by rudi** [comment]
Thanks for the report! Fixed and test case added.  (FWIW, the xtext branch already caught this error.)
