### ISSUE TITLE
`absc -d /` tries to delete the root directory

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#294]
The `-d` parameter should probably always name a relative directory name that is a subdirectory of the current directory?  On the other hand, `absc -d ../compiled-models/` should be ok

**Comment by larstvei** [comment]
Is it necessary to delete everything in the directory? If we know exactly what needs to be cleaned, just deleting those files/directories must be sufficient.

If that isn't an option, then I would suggest listing the files/directories that are about to be nuked, and asking the user if they're **really sure** they want to delete them. Unless the `-d` options isn't set, of course.

Generally, I don't think a compiler should _be able_ to delete files it hasn't produced.
