### ISSUE TITLE
Cowboy idle_timeout of 60s breaks long-running model API invocations

### ISSUE THREAD

**Issue by VolkerStolz** [abstools/abstools#301]
The current runtime uses Cowboy's default timeout of 60s. If a method call through the model API takes longer, Cowboy will drop the connection, which leads on the caller side e.g. to an `curl: (52) Empty reply from server`, and somehow leaves the affected object unusable.

Completely disabling `idle_timeout` might be `infinity`.

We could raise the default and/or make it configurable. Additionally, we might want to investigate what happens to the state of objects that get hit by that.

- https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_http/

**Comment by rudi** [comment]
I’d be ok with turning off timeouts until someone finds problems with that - we’re not going for the long-running, high-availability server market here :)
