### ISSUE TITLE
Can not complete the install

### ISSUE THREAD

**Issue by Yasqader** [abstools/abstools#316]
I add a plugin to eclipse recently, but something goes wrong (the error below), can anyone describe how to resolve it?

Cannot complete the install because some dependencies are not satisfiable org.eclipse.equinox.p2.iu; eu.hatsproject.costabs.feature.group [1.0.6.201212191721-svn15890,1.0.6.201212191721-svn15890] cannot be installed in this environment because its filte

Indeed i sent the error to https://bugs.eclipse.org and recived answer below

You should ask the people who provide it this question.  Maybe it can only be installed on Linux...

**Comment by rudi** [comment]
Hello Yasqader, the eclipse plugin has not been available or supported for many years.  Sadly, some documentation has not been rewritten yet to reflect that; help is welcome.

For editor and IDE integration, either of tree-sitter or LSP would be the way forward; help is welcome there as well.

**Comment by Yasqader** [comment]
hello rudi,
can you please tell me should i install ABS language package on LSP(microsoft language server protocol)?

**Comment by rudi** [comment]
Hello Yasqader, if I understood you correctly you're offering help in implementing LSP support for ABS?  If so, that would be fantastic!  Otherwise, we have simple syntax highlighting for Atom and VS Code, and a more complete Emacs mode for ABS; see the documentation at https://abs-models.org/getting_started/editor-support/.

**Comment by Yasqader** [comment]
Emacs was a good suggestion thank you very much.But it seems that Emacs has a common problem about absc. Now i have this error on Emacs " absc --erlang "DataTransmitted.abs" 
/bin/bash: line 1: absc: command not found " . I tried "M-x load-library RET abs RET " on Ubuntu and this command leads to "cannot open load file: no such file or directory, abs".  Where can i find absc and how can i set it. Should i change environmental variable?
Thank you for your guidance and support.

**Comment by rudi** [comment]
Hi, https://abs-models.org/getting_started/editor-support/ says "Installation instructions are at https://github.com/abstools/abs-mode".  https://github.com/abstools/abs-mode, under "Common Problems", explains how to set the variable `abs-compiler-program`.

Maybe these instructions are a bit too hidden; I'll think about how to reformulate the README file to make this more prominent.  If you have any suggestions there, I'd be grateful.

(You do have abs itself installed, right?  If so, is `absc` on your path, and are you on macOS?  If so, install the `exec-path-from-shell` package as well, as mentioned in the second paragraph of the "Common Problems" section.)
