### ISSUE TITLE
Integrate jabsc into eclipse-plugin

### ISSUE THREAD

**Issue by nobeh** [abstools/abstools#5]
[`jabsc`](https://github.com/CrispOSS/jabsc) is the currently being developed ABS to Java compiler using [`jabs`](https://github.com/CrispOSS/abs-api-parent) which is implementation of ABS semantics as an API in Java 8. Integrate this compiler into the current eclipse-plugin.

**Comment by nobeh** [comment]
@vlad-serbanescu @bezirg

**Comment by nobeh** [comment]
Comment form @VolkerStolz in email:

> Behrooz, if you don’t plan to support the sequence-diagram based editor,
you can drop this dependency in your branch. Also, maybe you don’t want
to overwrite the existing plugin — it’s bad design that all the
functionality was integrated there, it would be better if the new plugin
is stand-alone, i.e.. just the button. But then, since it is so small,
maybe that’s over engineering.

**Comment by nobeh** [comment]
OK, I have a running version of this integration with the following summary:

Integrate jabsc into eclipse plugin 

- Add local dependencies for jabs and jabsc to plugin runtime
- Introduce the UI button for Compilation and Running. The latter
is not yet supported.
- Restore previous backend integration so that the two are separate.

NOTE the current way of adding jabs(c) dependencies are very suboptimal.
This means that every time it is needed to update `lib/` folder which is
far away from standards. We need to find a way to property add OSGi/Maven
dependencies to the plugin to resolve jabs(c) at runtime.

I'll try to find a better way for dependency management before completing
the branch and opening a PR.

**Comment by rudi** [comment]
On 2. aug. 2015, at 01:16, Behrooz Nobakht <notifications@github.com> wrote:

> OK, I have a running version of this integration with the following summary:
> 
> Integrate jabsc into eclipse plugin
> 
> Add local dependencies for jabs and jabsc to plugin runtime
> Introduce the UI button for Compilation and Running. The latter is not yet supported.
> Restore previous backend integration so that the two are separate.
> NOTE the current way of adding jabs(c) dependencies are very suboptimal.
> This means that every time it is needed to update lib/ folder which is
> far away from standards. We need to find a way to property add OSGi/Maven
> dependencies to the plugin to resolve jabs(c) at runtime.
> 
> I'll try to find a better way for dependency management before completing
> the branch and opening a PR.
> 

That sounds interesting.  Maybe we can break up the big archive containing both the compiler and the plugins as well using such an approach.

Rudi

**Comment by VolkerStolz** [comment]
On 04/08/15 11:40, Rudi Schlatte wrote:

> That sounds interesting. Maybe we can break up the big archive
> containing both the compiler and the plugins as well using such an approach.

Which big archive are you thinking about?

  -Volker

**Comment by rudi** [comment]
On 4. aug. 2015, at 11:56, Volker Stolz <notifications@github.com> wrote:

> On 04/08/15 11:40, Rudi Schlatte wrote:
> 
>> That sounds interesting. Maybe we can break up the big archive
>> containing both the compiler and the plugins as well using such an approach.
> 
> Which big archive are you thinking about?

abstools/abstools. It contains the compiler (frontend/) and the eclipse plugin.

**Comment by VolkerStolz** [comment]
On 04/08/15 11:58, Rudi Schlatte wrote:
>> On 04/08/15 11:40, Rudi Schlatte wrote:
>>
>>> That sounds interesting. Maybe we can break up the big archive
>>> containing both the compiler and the plugins as well using such an
> approach.
>>
>> Which big archive are you thinking about?
> 
> abstools/abstools. It contains the compiler (frontend/) and the eclipse
> plugin.

I think Behrooz was more thinking about the binary artifacts after
compilation.

  -Volker
